name: build

on:
  pull_request:
    branches:
      - 'alpha'
      - 'beta'
      - 'master'
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 14, 15]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci
        env:
          CI: true

      - name: Lint
        run: npm run lint

      - name: Check code format
        run: npm run format:check

      - name: Test
        run: npm run test
        env:
          CI: true

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Report coverage
        if: startsWith(matrix.node-version, '10') && github.event_name == 'push'
        run: npm run codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Deploy docs
        if: success() && startsWith(matrix.node-version, '10') && github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v2.3.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs

      # - name: Create release
      #   if: success() && startsWith(matrix.node-version, '10') && github.event_name == 'push'
      #   run: npm run semantic-release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
