name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 12]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install, test and build
        run: |
          yarn
          yarn lint
          yarn format:check
          yarn test
          yarn build
        env:
          CI: true

  report-coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: codecov/codecov-action@v1.0.2
        name: Report coverage
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  deploy-docs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - if: github.event_name != 'pull_request' && github.ref == 'master'
        name: Deploy docs
        uses: peaceiris/actions-gh-pages@v2.3.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name != 'pull_request' && github.ref == 'master'
        name: Create release
        run: yarn semantic-release
