name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 12]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          yarn
          yarn lint
          yarn format:check
          yarn test
          yarn build
        env:
          CI: true

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      - if: github.event_name != 'pull_request' && github.ref == 'master'
        run: yarn deploy-docs
      - if: github.event_name != 'pull_request' && github.ref == 'master'
        run: yarn semantic-release
