name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn --frozen-lockfile
        env:
          CI: true

      - name: Lint
        run: yarn lint

      - name: Check code format
        run: yarn format:check

      - name: Test
        run: yarn test
        env:
          CI: true

      - name: Build
        run: yarn build
        env:
          CI: true

      - name: Report coverage
        if: startsWith(matrix.node-version, '10')
        run: yarn codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  deploy-docs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - if: github.ref == 'master'
        name: Deploy docs
        uses: peaceiris/actions-gh-pages@v2.3.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - if: github.ref == 'master'
        name: Create release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
